name: Check Changes

on:
  push:
    branches:
      - main

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: get_changed_files
        run: |
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt

      - name: Show changed files
        run: cat changed_files.txt
