name: Display PR number

on:
  pull_request_review:
    types: [submitted]

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Display PR number
        run: echo ${{ github.event.pull_request.number }}
