name: PR number

on: [pull_request]

jobs:
  pull-request-open:
    runs-on: ubuntu-latest
    if: ${{ github.event.action }} == "opened"
    steps:
      - run: echo "PR-${{ github.event.number }} opened"

  pull-request-closed:
    runs-on: ubuntu-latest
    if: ${{ github.event.action }} == "closed"
    steps:
      - run: echo "PR-${{ github.event.number }} closed"      
